[tool.poetry]
name = "pywencai"
version = "0.2.0"
description = ""
authors = ["pluto <mayuanchi1029@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
PyExecJS = "^1.5.1"
requests = "^2.28.1"
pandas = "^1.5.0"

[tool.poetry.group.dev.dependencies]
notebook = "^6.4.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
